core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include("controller_stock.urls")),
    path('equipment/', include('equipment.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

controller_stock/models.py
from django.db import models
from equipment.models import Equipment
from controllers.models import UserTracking, TimeStampModel
from django.contrib.auth.models import User


class Location(TimeStampModel):
    TYPE_CHOICES = [
        ('estoque', 'Estoque'),
        ('cliente', 'Cliente'),
        ('tecnico', 'Técnico'),
    ]
    location = models.CharField(max_length=124, verbose_name='Local')
    type = models.CharField(
        max_length=124, verbose_name='Tipo', choices=TYPE_CHOICES)
    user = models.ForeignKey(User, on_delete=models.PROTECT,
                             verbose_name='Técnico', related_name='locations', null=True, blank=True)

    class Meta:
        verbose_name = 'Local'
        verbose_name_plural = 'Locais'
        ordering = ['location']

    def __str__(self) -> str:
        return str(self.location)


class Reason(TimeStampModel):
    reason = models.CharField(max_length=124, verbose_name='Motivo')

    class Meta:
        verbose_name = 'Motivo'
        ordering = ['reason']

    def __str__(self):
        return self.reason


class ControllerStock(UserTracking, TimeStampModel):
    equipment = models.OneToOneField(
        Equipment, on_delete=models.PROTECT, verbose_name='Equipamento', related_name='stocks',)
    location = models.ForeignKey(
        Location, on_delete=models.PROTECT, verbose_name='Local', related_name='stocks')
    reason = models.ForeignKey(
        Reason, on_delete=models.PROTECT, verbose_name='Motivo', related_name='controllers')
    observation = models.TextField(
        verbose_name='Observação', default='Estoque')

    class Meta:
        verbose_name = 'Controle Estoque'
        verbose_name_plural = 'Controle Estoque'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['location'])
        ]

    def __str__(self):
        return f'{self.equipment}, {self.location}'


class Tracking(UserTracking, TimeStampModel):
    equipment = models.ForeignKey(
        Equipment, on_delete=models.PROTECT, verbose_name='Equipamento', related_name='trackings')
    origin = models.ForeignKey(
        Location, on_delete=models.PROTECT, verbose_name='Origem', related_name='origins_trackings')
    destination = models.ForeignKey(
        Location, on_delete=models.PROTECT, verbose_name='Destino', related_name='destination_trackings')
    reason = models.ForeignKey(
        Reason, on_delete=models.PROTECT, verbose_name='Motivo', related_name='trackings')
    observation = models.TextField(
        verbose_name='Observação', default='Estoque')

    class Meta:
        verbose_name = 'Rastreio'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.equipment}'

equipment/models.py
from django.db import models
from controllers.models import TimeStampModel, UserTracking


class Brand(TimeStampModel):
    brand = models.CharField(
        max_length=124, unique=True, verbose_name='Marca')

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'
        ordering = ['brand']

    def save(self, *args, **kwargs):
        if self.brand:
            self.brand = self.brand.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.brand


class ModelEquipment(TimeStampModel):
    model = models.CharField(
        max_length=124, verbose_name='Modelo')
    brand = models.ForeignKey(
        Brand, on_delete=models.PROTECT, verbose_name='Marca', related_name='models')

    class Meta:
        verbose_name = 'Modelo do equipamento'
        verbose_name_plural = 'Modelos dos equipamentos'
        ordering = ['model']
        unique_together = ['model', 'brand']

    def save(self, *args, **kwargs):
        if self.model:
            self.model = self.model.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return str(f'{self.model}')


class Category(TimeStampModel):
    category = models.CharField(
        max_length=124, unique=True, verbose_name='Categoria')

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['category']

    def save(self, *args, **kwargs):
        if self.category:
            self.category = self.category.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.category


class StatusEquipment(TimeStampModel):
    status = models.CharField(
        max_length=72, unique=True, verbose_name='Status')

    class Meta:
        verbose_name = 'Status do equipamento'
        verbose_name_plural = 'Status dos equipamentos'
        ordering = ['status']

    def save(self, *args, **kwargs):
        if self.status:
            self.status = self.status.upper()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.status


class Equipment(UserTracking, TimeStampModel):
    brand = models.ForeignKey(
        Brand, on_delete=models.PROTECT, verbose_name='Marca', related_name='equipments')
    model = models.ForeignKey(ModelEquipment, on_delete=models.PROTECT,
                              verbose_name='Modelo', related_name='equipments')
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, verbose_name='Categoria', related_name='equipments')
    mac_address = models.CharField(
        max_length=124, verbose_name='Mac Address', unique=True)
    serial_number = models.CharField(
        max_length=124, verbose_name='Serial Number', unique=True)
    status = models.ForeignKey(StatusEquipment, on_delete=models.PROTECT,
                               related_name='equipments', verbose_name='Status')

    class Meta:
        verbose_name = 'Equipamento'
        verbose_name_plural = 'Equipamentos'
        ordering = ['model']

    def save(self, *args, **kwargs):
        if self.mac_address and self.serial_number:
            self.mac_address = self.mac_address.upper()
            self.serial_number = self.serial_number.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.model}'

core/templates/components/create_update_model.html
{% extends "_base.html" %}
{% load static %}

{% block title %}
    {% if not object %}
        ➕ Cadastrar {{ title }}
    {% else %}
         ✏️ Atualizar {{ title }}
    {% endif %}    
{% endblock %}


{% block content %}
<div class="container mx-auto p-6">
    
    {% if not object %}
        <h1 class="text-2xl font-bold mb-6">➕ Cadastrar {{ title }} </h1>
    {% else %}
        <h1 class="text-2xl font-bold mb-6">✏️ Atualizar {{ title }} </h1>
    {% endif %}
        
    
    <div class="bg-gray-800 p-6 rounded-lg shadow-md">  
        <form method="post" class="space-y-6">
            {% csrf_token %} 
        {% for field in form %}
        <div>
            <label for="{{ field.id_for_label }}" class="block text-sm font-medium ">
            {{ field.label }} {% if field.field.required %}*{% endif %}
            </label>
            {{ field }}
            {% if field.errors %}
            <p class="text-sm text-red-600">{{ field.errors|striptags }}</p>
            {% endif %}
        </div>
        {% endfor %}

        <!-- Botões --> 
         <div class="flex justify-end gap-4">
        <a href="{% url 'list_'|add:sufix_url %}" class="px-6 py-2 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 transition"> Cancelar </a> 
        <button type="submit" class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"> Salvar </button> 
        </div>
        </form>
    </div>
</div>
{% endblock %}

core/templates/components/filter.html
 <form method="get" class="mb-6 flex flex-col sm:flex-row gap-4">
        <!-- Campo de filtro -->
        <select
            name="location"
            class="w-full sm:w-1/4 px-4 py-2 bg-gray-800 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
            <option value="">Todos os locais</option>
            {% for loc in locations %}
                <option value="{{ loc.location }}" {% if request.GET.location == loc.location|stringformat:"s" %}selected{% endif %}>
                    {{ loc.location }}
                </option>
            {% endfor %}
        </select>
        <!-- Botão de pesquisa -->
        <button
            type="submit"
            class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
        >
            Filtrar
        </button>
    </form>

core/templates/components/list.html
{% extends "_base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="container mx-auto p-6">
    <h1 class="text-2xl font-bold mb-6">📋 Lista de {{ title }}</h1>

    <div class="flex justify-between mb-3">
            {% if add_filter %}
                <div class="grow">
                    {% include 'components/search.html' %}
                </div>
            {% endif %}
    <!-- Botão Criar Novo -->        
        <div class="flex-end">                            
            <a href="{% url 'create_'|add:sufix_url %}"
                class="px-5 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition">
                ➕ Novo {{ title }}
            </a>
        </div>
    </div>
     {% if title == 'Equipamento' %}
    <div class='flex justify-end'>
        <div>{% include 'components/uploadfile.html' %}</div>
    </div>
    {% endif %}
    <div class="overflow-x-auto shadow-md rounded-lg">
        {% if object_list %}
            <table class="min-w-full text-left border-collapse">
                <thead class="bg-gray-800">
                    <tr> 
                        <th class="px-4 py-2 text-left text-sm font-semibold">
                            {{ title }}
                        </th>
                        
                        {% if title == 'Modelo do equipamento' %}
                            <th class="px-4 py-2 text-left text-sm font-semibold">
                                Marca do Equipamento
                            </th>
                        {% endif %}
                                                 
                        <th class="px-4 py-2 text-right text-sm font-semibold">Ações</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200">
                    {% for obj in object_list %}
                        <tr class="hover:bg-gray-800">
                            
                            <td class="px-4 py-2 text-sm flex justify-between">
                                <span>{{ obj|upper }} </span>                                            
                             {% if obj.mac_address %}
                                <span class="text-right">Mac Address - {{ obj.mac_address}}</span>
                            {% endif %}
                            </td>
                            
                            {% if title == 'Modelo do equipamento' %}
                                <td class="px-4 py-2 text-sm">
                                    <span>{{ obj.brand|upper }} </span>
                                </td>
                            {% endif %}
                                
                            <td class="px-4 py-2 text-right space-x-2">
                                <a href="{% url 'update_'|add:sufix_url obj.id %}" 
                                   class="px-3 py-1 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm">Editar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="text-gray-600">Nenhum {{ title }} encontrado.</p>
        {% endif %}
    </div>
    {% include 'components/pagination.html' %}
</div>
{% endblock %}

core/templates/components/pagination.html
{% if is_paginated %}
  <div class="mt-6 flex justify-center space-x-2">

    {# Primeira + Anterior #}
    {% if page_obj.has_previous %}
      <a href="?page=1&q={{ request.GET.q }}&location={{ request.GET.location }}" 
         class="px-3 py-2 bg-gray-800 rounded hover:bg-gray-700">Primeira</a>
      <a href="?page={{ page_obj.previous_page_number }}&q={{ request.GET.q }}&location={{ request.GET.location }}" 
         class="px-3 py-2 bg-gray-800 rounded hover:bg-gray-700">Anterior</a>
    {% endif %}

    {# Reticências antes (se necessário) #}
    {% if page_obj.number > 3 %}
      <a href="?page=1&q={{ request.GET.q }}&location={{ request.GET.location }}" 
         class="px-3 py-2 bg-gray-800 rounded hover:bg-gray-700">1</a>
      <span class="px-3 py-2">…</span>
    {% endif %}

    {# Páginas vizinhas #}
    {% for num in page_obj.paginator.page_range %}
      {% if num >= page_obj.number|add:"-2" and num <= page_obj.number|add:"2" %}
        {% if num == page_obj.number %}
          <span class="px-3 py-2 bg-blue-600 text-white rounded">{{ num }}</span>
        {% else %}
          <a href="?page={{ num }}&q={{ request.GET.q }}&location={{ request.GET.location }}" 
             class="px-3 py-2 bg-gray-800 rounded hover:bg-gray-700">{{ num }}</a>
        {% endif %}
      {% endif %}
    {% endfor %}

    {# Reticências depois (se necessário) #}
    {% if page_obj.number < page_obj.paginator.num_pages|add:"-2" %}
      <span class="px-3 py-2">…</span>
      <a href="?page={{ page_obj.paginator.num_pages }}&q={{ request.GET.q }}&location={{ request.GET.location }}" 
         class="px-3 py-2 bg-gray-800 rounded hover:bg-gray-700">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}

    {# Próxima + Última #}
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}&location={{ request.GET.location }}" 
         class="px-3 py-2 bg-gray-800 rounded hover:bg-gray-700">Próxima</a>
      <a href="?page={{ page_obj.paginator.num_pages }}&q={{ request.GET.q }}&location={{ request.GET.location }}" 
         class="px-3 py-2 bg-gray-800 rounded hover:bg-gray-700">Última</a>
    {% endif %}

  </div>
{% endif %}

core/templates/components/search.html
<form method="get" class="mb-6 w-full flex flex-col sm:flex-row gap-4 ">
        <!-- Campo de busca -->
        <input 
            type="text" 
            name="search" 
            value="{{ request.GET.search }}" 
            placeholder="Buscar MAC ou SN..." 
            class="w-full sm:w-1/2 px-4 py-2 bg-gray-800 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-800"
        >
        <!-- Botão de pesquisa -->
        <button 
            type="submit" 
            class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
        >
            Pesquisar
        </button>
    </form>

core/templates/components/sidebar.html
 <!-- Sidebar Dinâmico -->
<aside 
    class="shadow-md flex flex-col transition-all duration-300"
    :class="open ? 'w-64' : 'w-20'"
>
    <!-- Header do Sidebar -->
    <div class="flex items-center justify-between p-3 border-b">
        <span class="text-xl font-bold truncate items-center gap-3 px-3 py-2" x-show="open">📋 Menu</span>
        <button 
            @click="open = !open"
            class="p-2 rounded hover:bg-gray-700 items-center gap-3 px-3 py-2"
         title="Menu">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
            </svg>
        </button>
    </div>

    <!-- Navegação -->
    <nav class="flex-1 p-4 space-y-2">
        
        {% if perms.controller_stock.view_controllerstock and not thecnical %}    
            <a href="{% url 'dashboard' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Dashboards">
                📊 <span x-show="open">Dashboards</span>
            </a>
        
        {% endif %}            
        
        {% if perms.controller_stock.view_controllerstock %}
            <a href="{% url 'stock' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Controle de equipamento">
            📦 <span x-show="open">Controle de equipamento</span>
        </a>
        {% endif %}            
        
        {% if perms.controller_stock.view_tracking %}
            <a href="{% url 'tracking' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Rastreamento">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><g fill="none"><path fill="url(#SVGTW2naeNJ)" d="M21 19c0 2.5-4.03 4-9 4s-9-1.5-9-4c0-2.406 4.03-4 9-4s9 1.5 9 4"/><path fill="url(#SVGcfH1icHa)" d="M12 2a7.5 7.5 0 0 0-7.5 7.5c0 1.932 1.064 3.8 2.268 5.316c1.22 1.537 2.678 2.829 3.655 3.622c.926.75 2.228.75 3.154 0c.977-.793 2.435-2.085 3.655-3.622C18.436 13.301 19.5 11.432 19.5 9.5A7.5 7.5 0 0 0 12 2"/><path fill="url(#SVG1e3cqb0x)" d="M14.5 9.5a2.5 2.5 0 1 1-5 0a2.5 2.5 0 0 1 5 0"/><defs><linearGradient id="SVGcfH1icHa" x1="1.219" x2="13.202" y1="-2.857" y2="16.549" gradientUnits="userSpaceOnUse"><stop stop-color="#f97dbd"/><stop offset="1" stop-color="#d7257d"/></linearGradient><linearGradient id="SVG1e3cqb0x" x1="9.79" x2="12.394" y1="9.721" y2="12.428" gradientUnits="userSpaceOnUse"><stop stop-color="#fdfdfd"/><stop offset="1" stop-color="#fecbe6"/></linearGradient><radialGradient id="SVGTW2naeNJ" cx="0" cy="0" r="1" gradientTransform="rotate(-10.678 100.2 -51.93)scale(14.3921 6.38107)" gradientUnits="userSpaceOnUse"><stop stop-color="#7b7bff"/><stop offset=".502" stop-color="#a3a3ff"/><stop offset="1" stop-color="#ceb0ff"/></radialGradient></defs></g></svg>
 <span x-show="open">Rastreamento</span>
            </a>
        {% endif %}
            
        
        {% if perms.equipment.view_equipment %}
            <a href="{% url 'list_equipment' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Equipamento">
            💻 <span x-show="open"> Equipamento</span>
        </a>
        {% endif %}
            
        
        {% if perms.controller_stock.view_reason %}
            <a href="{% url 'list_reason' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Motivos">
            📝 <span x-show="open">Motivos</span>
        </a>
        {% endif %}
            
        
        {% if perms.equipment.view_category %}
            <a href="{% url 'list_category' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Categorias de equipamento">
            🔖 <span x-show="open">Categorias de equipamento</span>
        </a>
        {% endif %}
            
        
        {% if perms.equipment.view_brand %}
            <a href=" {% url 'list_brand' %} " class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Marcas de Equipamento">
            🏷️ <span x-show="open">Marcas de Equipamento</span>
        </a>
        {% endif %}
            
        
        {% if perms.equipment.view_modelequipment %}
            <a href="{% url 'list_modelequipment' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Modelos de Equipamento">
            🔲 <span x-show="open">Modelos de Equipamento</span>
        </a>
        {% endif %}
            
        
        {% if perms.equipment.view_statusequipment %}
            <a href="{% url 'list_statusequipment' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Status de Equipamento">
            ✅ <span x-show="open">Status de Equipamento</span>
        </a>
        {% endif %}
                    
        {% if perms.controller_stock.view_location %}
            <a href="{% url 'list_location' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Localizações">
            📌 <span x-show="open">Localizações</span>
        </a>
        {% endif %}
            <a href="{% url 'detail_account' user.id %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Meu Perfil">
            👤 <span x-show="open">Meu Perfil</span>
        </a>
            
            <a href="{% url 'logout' %}" class="flex items-center gap-3 px-3 py-2 rounded hover:bg-gray-700 transition" title="Sair">
            🚪<span x-show="open">Sair</span>
        </a>

            
    </nav>
</aside>

core/templates/components/uploadfile.html
{% for message in messages %}
{% if 'success' in message.tags %}
  <li class="bg-green-100 border border-green-400 text-green-700 px-4 py-1 rounded" role="alert" style="max-width: 580px">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fechar"></button>
  </li>
{% else %}
  <li class='bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded' role="alert" style="max-width: 580px">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fechar"></button>
  </li>
{% endif %}
{% endfor %}
<form action="{% url 'uploadfile' %}" method="post" enctype="multipart/form-data" class="mb-6 w-full flex sm:flex-row gap-4 ">
    {% csrf_token %}
    <input type="file" name="file" id="file" required>
    <button type="submit" class="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition">Importar arquivo</button>
</form>